name = "GradedRingUtilities"
uuid = "ac2b5ee4-d872-4ff4-b600-35f8f75c8465"
authors = ["JJ Garzella <jjgarzella@gmail.com> and contributors"]
version = "0.0.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
